openfga:
  fgaApiUrl: http://localhost:4000
  fgaStoreId:
  fgaStoreName: test
#  fgaAuthModelSchema: classpath:/example-auth-model.json
#  fgaInitialRelationshipTuple: classpath:/example-relationship-tuple.json

logging:
  level:
    root: WARN
    com:
      fga:
        example: TRACE
    org:
      springframework:
        security: DEBUG
