name:  Checks

on: [pull_request, push]

jobs:
  build:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run Gradle check task
        run: |
          cd simple-auth
          ./gradlew check --continue